
---
title: "LoadPackageFromNet"
output:
  html_document:
    toc: true
---


```{r}
if(!require("devtools")) install.packages("devtools")
devtools::install_github("Microsoft/AzureSMR")
library(AzureSMR)
```


```{r}
library(AzureSMR)
library(SparkR)
```


```{r}
############## Use SparkR  ##############

# SQL connection thru R
from pyspark.sql.functions import lit
from pyspark.sql.functions import monotonically_increasing_id
from pyspark.sql import functions as F
from pyspark.sql.window import Window as W

# SQL server connection Details ----------
server = 'sqldbplatingnum.database.windows.net'
database = 'cozydb'
username = 'platingnum'
password = 'D0wnl0ad!'
driver= '{ODBC Driver 13 for SQL Server}'
connectionProperties = {
  "user" : username,
  "password" : password
}

```


```{r}
# ADL Azure data lake connection Details 
spark.conf.set("dfs.adls.oauth2.access.token.provider.type", "ClientCredential")
spark.conf.set("dfs.adls.oauth2.client.id", "4d91dcd1-4dfe-4a16--0924b8eddbde")
spark.conf.set("dfs.adls.oauth2.credential", "cb0a5yRo8sgaB//aZL/5gKmRsZ4=")
spark.conf.set("dfs.adls.oauth2.refresh.url", "https://login.microsoftonline.com/-2442-49ca-bb06-466903cd6dd6/oauth2/token")
```

